"""
PySpark ETL — plan_id=plan_1783668374
Generated by: Agent Dhara
Policy:
plan_id: plan_1783668374
# row_preservation: subset drops allowed
# join_strategy: none
# privacy: none
# outlier_strategy: flag
# required_columns: []
# exclude_columns: []
# valid_values: []
"""
from __future__ import annotations

import logging
import os
from typing import Optional
from pyspark.sql import functions as F
from pyspark.sql import DataFrame

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('agent_dhara')

def _resolve_data_path(location: str) -> str:
    """Resolve path relative to the attached default Lakehouse."""
    loc = (location or "").strip()
    if not loc or loc == "unknown":
        raise ValueError("location is missing")
    if loc.lower().startswith(("abfss://", "wasbs://", "https://", "http://")):
        return loc
    # In Fabric Notebooks, the default attached lakehouse is mounted under /lakehouse/default
    return f"/lakehouse/default/{loc.lstrip('/')}"

def _require_columns(df, required: list, label: str) -> None:
  """Fail fast if required columns are missing."""
  missing = [c for c in required if c not in df.columns]
  if missing:
    raise ValueError(f"{label}: missing required columns: {missing}")


def _warn_duplicate_keys(df, key_col: str, label: str) -> None:
  """Log possible duplicate join keys (single scan — approx distinct, no full shuffle)."""
  import logging
  import os
  if key_col not in df.columns:
    return
  if os.environ.get("DHARA_ETL_CHECK_DUP_KEYS", "1").strip().lower() in ("0", "false", "no"):
    return
  row = (
    df.agg(
      F.count(F.col(key_col)).alias("_n"),
      F.approx_count_distinct(F.col(key_col)).alias("_d"),
    )
    .first()
  )
  if not row:
    return
  n, d = int(row["_n"] or 0), int(row["_d"] or 0)
  if n > 0 and d > 0 and n > d:
    logging.getLogger("agent_dhara").warning(
      "%s: ~%d possible duplicate key value(s) on %s (approx_count_distinct)",
      label,
      n - d,
      key_col,
    )


def _warn_nulls_in_columns(df, columns: list, label: str) -> None:
  """Cheap null probe: limit(1) per column — does not scan full table."""
  import logging
  for col in columns or []:
    if col not in df.columns:
      continue
    if df.filter(F.col(col).isNull()).limit(1).count() > 0:
      logging.getLogger("agent_dhara").warning(
        "%s: column %s has null values after transform", label, col
      )


def _log_row_count(df, label: str) -> None:
  """Optional row count log (set DHARA_ETL_LOG_ROW_COUNTS=1)."""
  import logging
  import os
  if os.environ.get("DHARA_ETL_LOG_ROW_COUNTS", "0").strip().lower() not in ("1", "true", "yes"):
    return
  logging.getLogger("agent_dhara").info("%s: row_count=%s", label, df.count())

def _iqr_bounds(df, col: str, multiplier: float = 1.5):
    """Return (stats_row, iqr, lower, upper) for outlier transforms."""
    row = df.select(
        F.percentile_approx(F.col(col), 0.25).alias("q1"),
        F.percentile_approx(F.col(col), 0.75).alias("q3"),
        F.percentile_approx(F.col(col), 0.50).alias("median"),
    ).first()
    iqr = float(row["q3"] - row["q1"])
    lower = float(row["q1"] - multiplier * iqr)
    upper = float(row["q3"] + multiplier * iqr)
    return row, iqr, lower, upper

def _prefix_columns(df, prefix: str, except_cols: list):
    """Prefix right-side columns before join to avoid duplicate names."""
    for c in df.columns:
        if c not in except_cols:
            df = df.withColumnRenamed(c, f"{prefix}_{c}")
    return df

def transform_data_quality_issues_v2_json(df: DataFrame, all_dfs: Optional[dict] = None) -> DataFrame:
    out = df
    out = out.withColumn('country', F.trim(F.col('country').cast("string")))
    out = out.withColumn('name', F.trim(F.col('name').cast("string")))
    out = out.withColumn('user_id', F.trim(F.col('user_id').cast("string")))
    out = out.withColumn('country', F.lower(F.col('country').cast("string")))
    out = out.withColumn('name', F.lower(F.col('name').cast("string")))
    # WARNING: fill_value is None for column country — using empty string default
    out = out.withColumn('country', F.coalesce(F.col('country'), F.lit("")))
    out = out.withColumn('user_id', F.coalesce(F.col('user_id'), F.lit(14998.8414)))
    out = out.withColumn('user_id', F.when(F.col('user_id') == 0, F.lit(None)).otherwise(F.col('user_id')))
    out = out.withColumn('user_id', F.col('user_id').cast('double'))
    _stats, _iqr, _lower, _upper = _iqr_bounds(out, 'user_id', multiplier=1.5)
    out = out.withColumn('user_id_outlier_flagged', ((F.col('user_id') < F.lit(_lower)) | (F.col('user_id') > F.lit(_upper))) & F.col('user_id').isNotNull())
    out = out.dropDuplicates(['user_id'])
    return out

DATASETS = ['data_quality_issues_v2.json']

# ── OUTPUT CONTRACT ──
#   data_quality_issues_v2.json: json -> cleaned/data_quality_issues_v2_json_cleaned.json
OUTPUT_PATHS: dict = {}

def run_pipeline(spark):
    dfs = {}
    # Load (connector manifest — use _resolve_data_path for blob/SQL)
    # data_quality_issues_v2.json: fabric_files_zone (json) @ Files/raw/data_quality_issues_v2_json
    dfs["data_quality_issues_v2.json"] = spark.read.json(_resolve_data_path("Files/raw/data_quality_issues_v2_json"))
    
    if "data_quality_issues_v2.json" in dfs:
        dfs["data_quality_issues_v2.json"] = transform_data_quality_issues_v2_json(dfs["data_quality_issues_v2.json"], dfs)
        _log_row_count(dfs["data_quality_issues_v2.json"], "data_quality_issues_v2.json")
    # Write cleaned per-dataset outputs (format matches manifest; XML -> parquet)
    if "data_quality_issues_v2.json" in dfs:
        _out = _resolve_data_path("cleaned/data_quality_issues_v2_json_cleaned.json")
        OUTPUT_PATHS['data_quality_issues_v2.json'] = _out
        logging.getLogger('agent_dhara').info('Writing %s -> %s', 'data_quality_issues_v2.json', _out)
        dfs["data_quality_issues_v2.json"].write.format("delta").mode("overwrite").save(_resolve_data_path("Tables/data_quality_issues_v2_json_clean"))
        spark.sql("DROP TABLE IF EXISTS data_quality_issues_v2_json_clean")
        spark.sql("CREATE TABLE data_quality_issues_v2_json_clean USING delta LOCATION '" + _resolve_data_path("Tables/data_quality_issues_v2_json_clean") + "'")
    
    return dfs, OUTPUT_PATHS

# Fabric notebooks pre-inject 'spark'; fall back to creating one for local dev.
try:
    spark  # type: ignore[name-defined]
except NameError:
    from pyspark.sql import SparkSession
    spark = SparkSession.builder.appName("AgentDharaETL").getOrCreate()
_dfs, _paths = run_pipeline(spark)