"""
PySpark ETL — plan_id=plan_1784528263
Generated by: Agent Dhara
Policy:
plan_id: plan_1784528263
# row_preservation: subset drops allowed
# join_strategy: none
# privacy: none
# outlier_strategy: flag
# required_columns: []
# exclude_columns: []
# valid_values: []
"""
from __future__ import annotations

import logging
import os
from typing import Optional
from pyspark.sql import functions as F
from pyspark.sql import DataFrame

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('agent_dhara')

def _resolve_data_path(location: str) -> str:
    """Resolve path relative to the attached default Lakehouse using ABFSS."""
    loc = (location or "").strip()
    if not loc or loc == "unknown":
        raise ValueError("location is missing")
    if loc.lower().startswith(("abfss://", "http" + "s://", "http" + "://")):
        return loc
    clean_loc = loc.lstrip("/")
    # Ensure the mandatory Files/ or Tables/ prefix is present
    if not clean_loc.startswith(("Files/", "Tables/")):
        clean_loc = f"Files/{clean_loc}"
        
    # Attempt to resolve from spark config dynamically
    try:
        from pyspark.sql import SparkSession
        spark = SparkSession.builder.getOrCreate()
        ws_id = spark.conf.get("trident.workspace.id") or spark.conf.get("spark.workspace.id")
        lh_id = spark.conf.get("trident.lakehouse.id") or spark.conf.get("spark.lakehouse.id")
    except Exception:
        ws_id = None
        lh_id = None
        
    # Fallback to hardcoded values from deployment configuration
    if not ws_id or not lh_id:
        ws_id = ""
        lh_id = ""
        
    if ws_id and lh_id:
        return f"abfss://{ws_id}@onelake.dfs.fabric.microsoft.com/{lh_id}/{clean_loc}"
        
    return f"/lakehouse/default/{clean_loc}"

def _require_columns(df, required: list, label: str) -> None:
  """Fail fast if required columns are missing."""
  missing = [c for c in required if c not in df.columns]
  if missing:
    raise ValueError(f"{label}: missing required columns: {missing}")


def _warn_duplicate_keys(df, key_col: str, label: str) -> None:
  """Log possible duplicate join keys (single scan — approx distinct, no full shuffle)."""
  import logging
  import os
  if key_col not in df.columns:
    return
  if os.environ.get("DHARA_ETL_CHECK_DUP_KEYS", "1").strip().lower() in ("0", "false", "no"):
    return
  row = (
    df.agg(
      F.count(F.col(key_col)).alias("_n"),
      F.approx_count_distinct(F.col(key_col)).alias("_d"),
    )
    .first()
  )
  if not row:
    return
  n, d = int(row["_n"] or 0), int(row["_d"] or 0)
  if n > 0 and d > 0 and n > d:
    logging.getLogger("agent_dhara").warning(
      "%s: ~%d possible duplicate key value(s) on %s (approx_count_distinct)",
      label,
      n - d,
      key_col,
    )


def _warn_nulls_in_columns(df, columns: list, label: str) -> None:
  """Cheap null probe: limit(1) per column — does not scan full table."""
  import logging
  for col in columns or []:
    if col not in df.columns:
      continue
    if df.filter(F.col(col).isNull()).limit(1).count() > 0:
      logging.getLogger("agent_dhara").warning(
        "%s: column %s has null values after transform", label, col
      )


def _log_row_count(df, label: str) -> None:
  """Log row count for audit trail."""
  import logging
  logging.getLogger("agent_dhara").info("%s: row_count=%s", label, df.count())

def _iqr_bounds(df, col: str, multiplier: float = 1.5):
    """Return (stats_row, iqr, lower, upper) for outlier transforms."""
    row = df.select(
        F.percentile_approx(F.col(col), 0.25).alias("q1"),
        F.percentile_approx(F.col(col), 0.75).alias("q3"),
        F.percentile_approx(F.col(col), 0.50).alias("median"),
    ).first()
    if not row or row["q1"] is None or row["q3"] is None:
        return row, 0.0, -float('inf'), float('inf')
    iqr = float(row["q3"] - row["q1"])
    lower = float(row["q1"] - multiplier * iqr)
    upper = float(row["q3"] + multiplier * iqr)
    return row, iqr, lower, upper

def _prefix_columns(df, prefix: str, except_cols: list):
    """Prefix right-side columns before join to avoid duplicate names."""
    for c in df.columns:
        if c not in except_cols:
            df = df.withColumnRenamed(c, f"{prefix}_{c}")
    return df

def transform_data_quality_issues_csv(df: DataFrame, all_dfs: Optional[dict] = None) -> DataFrame:
    out = df
    # Step: trim on email
    out = out.withColumn('email', F.trim(F.col('email').cast("string")))
    # Step: trim on id
    out = out.withColumn('id', F.trim(F.col('id').cast("string")))
    # Step: trim on name
    out = out.withColumn('name', F.trim(F.col('name').cast("string")))
    # Step: lowercase on name
    out = out.withColumn('name', F.lower(F.col('name').cast("string")))
    # Step: sanitize_email on email
    out = out.withColumn('email', F.lower(F.trim(F.col('email').cast("string"))))
    out = out.withColumn('email', F.when(F.col('email').rlike(r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'), F.col('email')).otherwise(None))
    # Step: zero_to_null on id
    out = out.withColumn('id', F.when((F.col('id') == 0) | (F.col('id') == '0'), F.lit(None)).otherwise(F.col('id')))
    # Step: replace_sentinel_values on id
    out = out.withColumn('id', F.when(F.col('id').isin(['-999', '-999.0', '-9999', '-9999.0', '999', '999.0', '9999', '9999.0', '99999', '99999.0', '999999', '999999.0', -999, -999.0, -9999, -9999.0, 999, 999.0, 9999, 9999.0, 99999, 99999.0, 999999, 999999.0]), F.lit(None)).otherwise(F.col('id')))
    # Step: coerce_numeric on id
    # Coerce numeric on key: keep as string to prevent loss of leading zeros or alphanumeric chars
    out = out.withColumn('id', F.trim(F.col('id').cast('string')))
    # Step: fill_nulls_simple on email
    # Warning: no fill_strategy for email; keeping original values as-is
    # Step: fill_or_drop on id
    # Warning: no fill_strategy for id; keeping original values as-is
    # Step: fill_nulls_simple on name
    # Warning: no fill_strategy for name; keeping original values as-is
    # Step: deduplicate on [Row-level]
    _before = out.count()
    out = out.dropDuplicates()
    logger.info('deduplicate: dropped %d rows', _before - out.count())
    return out

DATASETS = ['data_quality_issues.csv']

# ── OUTPUT CONTRACT ──
#   data_quality_issues.csv: csv -> Tables/data_quality_issues_csv_clean
OUTPUT_PATHS: dict = {}

def run_pipeline(spark):
    dfs = {}
    # Load (connector manifest — use _resolve_data_path for blob/SQL)
    # data_quality_issues.csv: fabric_files_zone (csv) @ Files/raw/data_quality_issues_csv.csv
    dfs["data_quality_issues.csv"] = spark.read.option('header', 'true').option('inferSchema', 'true').csv(_resolve_data_path("Files/raw/data_quality_issues_csv.csv"))
    
    if "data_quality_issues.csv" in dfs:
        dfs["data_quality_issues.csv"] = transform_data_quality_issues_csv(dfs["data_quality_issues.csv"], dfs)
        _log_row_count(dfs["data_quality_issues.csv"], "data_quality_issues.csv")
    # Write cleaned per-dataset outputs (format matches manifest; XML -> parquet)
    if "data_quality_issues.csv" in dfs:
        _out = _resolve_data_path("Tables/data_quality_issues_csv_clean")
        OUTPUT_PATHS['data_quality_issues.csv'] = _out
        logger.info('Writing %s -> %s', 'data_quality_issues.csv', _out)
        dfs["data_quality_issues.csv"].write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("data_quality_issues_csv_clean")
    
    return dfs, OUTPUT_PATHS

# Fabric notebooks pre-inject 'spark'; fall back to creating one for local dev.
try:
    spark  # type: ignore[name-defined]
except NameError:
    from pyspark.sql import SparkSession
    spark = SparkSession.builder.appName("AgentDharaETL").getOrCreate()
_dfs, _paths = run_pipeline(spark)