import sqlite3
import json
import os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
db_path = os.path.join(root, "output", "chat_sessions.sqlite3")
print("Connecting to:", db_path)

conn = sqlite3.connect(db_path)
cursor = conn.cursor()
cursor.execute("SELECT payload_json FROM sessions WHERE session_id = 'a3447b6b-1763-4282-82c5-73b5a32119fc'")
row = cursor.fetchone()

if row:
    payload = json.loads(row[0])
    print("\nSession ID: a3447b6b-1763-4282-82c5-73b5a32119fc")
    print("Selected Tables:", payload.get("selected_tables"))
    print("Selected Table:", payload.get("selected_table"))
    print("Selected Source:", payload.get("selected_source"))
    
    ctx = payload.get("context", {})
    flow = ctx.setdefault("etl_flow", {})
    print("Flow Keys:", list(flow.keys()))
    print("Flow Phase:", flow.get("phase"))
    print("Flow Target Engine:", flow.get("target_engine"))
    print("Flow Codegen Engine:", flow.get("codegen_engine"))
    print("Flow Generated By:", flow.get("generated_by"))
    print("Flow Generation Mode:", flow.get("generation_mode"))
    
    plan = flow.get("approved_plan", {})
    if plan:
        print("Plan Generation Mode:", plan.get("generation_mode"))
        datasets = plan.get("datasets", {})
        for name, ds_data in datasets.items():
            print(f"\nDataset: {name}")
            print("  SCD Type:", ds_data.get("scd_type"))
            steps = ds_data.get("steps", [])
            print("  Steps:")
            for s in steps:
                print(f"    - {s.get('action')} on {s.get('column')}")
    
    plan = flow.get("approved_plan", {})
    print("\nApproved Plan Datasets:", list(plan.get("datasets", {}).keys()) if plan else None)
    
    sql_execution_result = flow.get("sql_execution_result", {})
    print("\nSQL Execution Result:")
    print(json.dumps(sql_execution_result, indent=2))
        
    fabric_mirror_result = flow.get("fabric_mirror_result", {})
    print("\nFabric Mirror Result:", json.dumps(fabric_mirror_result, indent=2))
    
    # Save the generated SQL code to a file so we can inspect it
    sql_code = flow.get("code", "")
    if sql_code:
        out_sql_path = os.path.join(root, "scratch", "current_session_sql.sql")
        with open(out_sql_path, "w", encoding="utf-8") as f:
            f.write(sql_code)
        print(f"\nSaved generated SQL ({len(sql_code)} chars) to {out_sql_path}")
else:
    print("Session not found.")
conn.close()
