import sys
import os

backend_dir = r"c:\Users\srevanku\OneDrive - Capgemini\Desktop\New folder (2)\DHARA-GX\Agent Dhara Backend"
sys.path.append(backend_dir)

from agent.etl_handlers import etl_generate_code, etl_confirm_plan

sid = "dca49baa-a68d-4861-9393-511fe4c6e6fd"
print(f"Testing session {sid}...")

engines = ["python", "sql", "pyspark", "adf"]
for eng in engines:
    print(f"\n--- Testing Code Gen for Engine: {eng} ---")
    try:
        # Confirm plan to move it to 'approved' phase
        conf = etl_confirm_plan(sid)
        print("Plan Confirmation Ok:", conf.get("ok"), "Phase:", conf.get("approved_plan", {}).get("phase") if conf.get("approved_plan") else "unknown")
        
        res = etl_generate_code(sid, engine=eng, codegen_mode="template")
        print("Success (ok):", res.get("ok"))
        print("Error Key:", res.get("error"))
        print("Message:", res.get("message"))
        print("Validation errors:", res.get("validation_errors"))
        print("Generated By:", res.get("generated_by"))
        code = res.get("code") or ""
        print(f"Code Preview (first 150 chars):\n{code[:150]}")
    except Exception as e:
        print("Exception occurred:", e)
