# Re-export key components of chat_graph to preserve backward compatibility.
from __future__ import annotations

# Re-export session store and other functions for patching in tests
from agent.session_store import load_session, save_session, add_experience, list_recent_experiences, SessionJSONEncoder
from agent.model_config import load_llm_config

from agent.chat_graph.state import ChatState
from agent.chat_graph.helpers import (
    _flow_options,
    _prompt_choose_action,
    _first_location_index,
    _render_report_markdown,
    _render_report_html,
    _override_source_root_for_datasets,
    _theme_wrap_html,
    _html_table,
    _md_escape,
    _make_validation,
    _validate_schema_markdown,
    _validate_metadata_markdown,
    _validate_report_payload,
    _build_report_tables_markdown,
    _write_report_artifacts,
    _pick_single_active_dataset,
    _dataset_null_percent_rank,
    _assessment_signature,
    _router_assessment_hints,
    _ensure_latest_assessment,
    _user_asks_selection_status,
    _user_wants_narrative_report_summary,
    _user_asks_relationships_focus,
    _truncate_summary_text,
    _markdown_narrative_assessment_summary,
    _cardinality_glossary_line,
    _load_sample_dfs_for_discovery,
)
from agent.chat_graph.llm import (
    _MASTER_SYSTEM,
    UserIntent,
    SEMANTIC_UTTERANCES,
    _EMBEDDING_CACHE,
    _get_embeddings,
    get_semantic_match,
    _get_llm_client_langchain,
    _classify_intent_structured,
    map_intent_to_action,
    _llm_plan,
)
from agent.chat_graph.nodes import (
    _node_show_cleaning_recommendations,
    _node_show_transform_suggestions,
    _node_show_null_columns,
    _node_dq_overview,
    _node_dq_duplicates,
    _node_relationships_overview,
    _node_summarize_report,
    _node_extract_columns,
    _node_load_session,
    _node_route,
    _node_show_selection_status,
    _node_help,
    _node_reset_flow,
    _node_back_flow,
    _node_list_sources,
    _node_select_source,
    _node_set_action,
    _azure_blob_locations,
    _node_list_blob_files,
    _node_select_blob_files,
    _filesystem_locations,
    _node_list_local_files,
    _node_select_local_files,
    _selected_file_mode_and_names,
    _reset_file_preview_paging,
    _node_preview_selected_file,
    _node_show_file_schema,
    _node_show_file_metadata,
    _node_generate_report_selected_files,
    _node_assess_selected_local_files,
    _node_assess_selected_files,
    _parse_view_mode,
    _node_preview_local_file,
    _node_preview_blob_file,
    _node_list_tables,
    _node_select_tables,
    _node_assess_selected_tables,
    _node_generate_report_selected,
    _node_select_table,
    _node_show_schema,
    _node_preview_table,
    _node_show_metadata,
    _node_dq_table,
    _node_nl_query,
    _node_save_session,
    _convo_followup_options,
    _apply_formatter,
    _node_convo_top_issues,
    _node_convo_issue_filter,
    _node_convo_triage,
    _node_convo_cross_dataset,
    _node_convo_clarify,
    _node_convo_boundary_ood,
    _node_convo_boundary_adv,
    _node_convo_etl_guidance,
    _node_build_etl_plan,
    _node_generate_etl_code,
    _node_show_etl_plan,
    _node_confirm_etl_plan,
    _node_capture_business_rules,
    _node_download_etl_code,
    _node_discover_semantic_rules,
)
from agent.chat_graph.graph import build_chat_graph, run_chat

__all__ = [
    "ChatState",
    "build_chat_graph",
    "run_chat",
    "load_session",
    "save_session",
    "add_experience",
    "list_recent_experiences",
    "SessionJSONEncoder",
    "load_llm_config",
]
